import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import GridPattern from "@/components/ui/grid-pattern";
import { Montserrat, Poppins } from 'next/font/google'
import { cn } from "@/lib/utils";
import { Providers } from "@/components/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Montserrat({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
          <GridPattern width={50} height={50} x={-1} y={-1} className={cn("[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)] -z-10")}/>
        </Providers>
      </body>
    </html>
  );
}
