import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import GridPattern from "@/components/ui/grid-pattern";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${""} antialiased`}
      >
        <Navbar/>
        {children}
        <GridPattern
        width={50}
        height={50}
        x={-1}
        y={-1}
        className={cn(
          "[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)] ",
        )}
      />
      </body>
    </html>
  );
}
